import Head from 'next/head';
// import {BsFillMoonStarsFill} from 'react-icons/bs';




export default function Home() {
  return (
    <div>
      <Head>
        <title>Equality72521</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <section className='bg-blue-700 h-screen  '>
          <nav className='py-10 mb-12 flex justify-between '>
            <h1>Daily News</h1>
            <ul>
              <li>
              {/* <BsFillMoonStarsFill /> */}
              </li>
              <li><a herf='#'>About Me</a></li>
            </ul>
          </nav>
        </section>
      </main>
      </div>
               
          
  );
}
